// AUTO-GENERATED by scripts/sync-migrations.ts — do not edit. Run `npm run db:generate`.
export interface Migration { name: string; statements: string[] }
export const migrations: Migration[] = [
  {
    "name": "0000_premium_sandman",
    "statements": [
      "CREATE TABLE `blog_posts` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`slug` text NOT NULL,\n\t`title` text NOT NULL,\n\t`excerpt` text DEFAULT '' NOT NULL,\n\t`content_markdown` text DEFAULT '' NOT NULL,\n\t`cover_image` text,\n\t`tags` text,\n\t`external_url` text,\n\t`reading_minutes` integer,\n\t`published_at` text NOT NULL,\n\t`published` integer DEFAULT true NOT NULL,\n\t`created_at` text,\n\t`updated_at` text\n);",
      "CREATE UNIQUE INDEX `blog_posts_slug_unique` ON `blog_posts` (`slug`);",
      "CREATE TABLE `education` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`degree` text NOT NULL,\n\t`institution` text NOT NULL,\n\t`location` text,\n\t`start_year` text,\n\t`end_year` text,\n\t`thesis` text,\n\t`thesis_url` text,\n\t`code_url` text,\n\t`coursework` text,\n\t`description` text,\n\t`sort_order` integer DEFAULT 0 NOT NULL\n);",
      "CREATE TABLE `experience` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`role` text NOT NULL,\n\t`organization` text NOT NULL,\n\t`organization_url` text,\n\t`location` text,\n\t`start_date` text,\n\t`end_date` text,\n\t`description` text,\n\t`sort_order` integer DEFAULT 0 NOT NULL\n);",
      "CREATE TABLE `messages` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`full_name` text NOT NULL,\n\t`email` text NOT NULL,\n\t`message` text NOT NULL,\n\t`created_at` text NOT NULL,\n\t`read` integer DEFAULT false NOT NULL\n);",
      "CREATE TABLE `news` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`date` text NOT NULL,\n\t`title` text NOT NULL,\n\t`body_markdown` text DEFAULT '' NOT NULL,\n\t`category` text DEFAULT 'News' NOT NULL,\n\t`url` text,\n\t`published` integer DEFAULT true NOT NULL,\n\t`created_at` text,\n\t`updated_at` text\n);",
      "CREATE TABLE `press` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`date` text NOT NULL,\n\t`outlet` text NOT NULL,\n\t`title` text NOT NULL,\n\t`description` text DEFAULT '' NOT NULL,\n\t`video_url` text,\n\t`image` text,\n\t`url` text,\n\t`language` text,\n\t`published` integer DEFAULT true NOT NULL,\n\t`sort_order` integer DEFAULT 0 NOT NULL\n);",
      "CREATE TABLE `profile` (\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`full_name` text NOT NULL,\n\t`short_name` text,\n\t`job_title` text NOT NULL,\n\t`tagline` text,\n\t`avatar` text,\n\t`about_markdown` text DEFAULT '' NOT NULL,\n\t`email` text,\n\t`secondary_email` text,\n\t`phone` text,\n\t`location` text,\n\t`affiliation` text,\n\t`affiliation_url` text,\n\t`cv_url` text,\n\t`map_embed_url` text,\n\t`site_title` text,\n\t`site_description` text,\n\t`footer_text` text,\n\t`updated_at` text\n);",
      "CREATE TABLE `projects` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`slug` text NOT NULL,\n\t`title` text NOT NULL,\n\t`category` text DEFAULT 'Research' NOT NULL,\n\t`summary` text DEFAULT '' NOT NULL,\n\t`content_markdown` text DEFAULT '' NOT NULL,\n\t`image` text,\n\t`url` text,\n\t`code_url` text,\n\t`partners` text,\n\t`start_year` text,\n\t`end_year` text,\n\t`status` text DEFAULT 'Ongoing' NOT NULL,\n\t`featured` integer DEFAULT false NOT NULL,\n\t`published` integer DEFAULT true NOT NULL,\n\t`sort_order` integer DEFAULT 0 NOT NULL,\n\t`created_at` text,\n\t`updated_at` text\n);",
      "CREATE UNIQUE INDEX `projects_slug_unique` ON `projects` (`slug`);",
      "CREATE TABLE `publications` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`year` integer NOT NULL,\n\t`authors` text NOT NULL,\n\t`title` text NOT NULL,\n\t`venue` text NOT NULL,\n\t`venue_short` text,\n\t`type` text DEFAULT 'Conference' NOT NULL,\n\t`paper_url` text,\n\t`pdf_url` text,\n\t`code_url` text,\n\t`doi` text,\n\t`abstract` text,\n\t`award` text,\n\t`bibtex` text,\n\t`status` text DEFAULT 'Published' NOT NULL,\n\t`highlight` integer DEFAULT false NOT NULL,\n\t`published` integer DEFAULT true NOT NULL,\n\t`sort_order` integer DEFAULT 0 NOT NULL,\n\t`created_at` text,\n\t`updated_at` text\n);",
      "CREATE TABLE `research_areas` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`title` text NOT NULL,\n\t`description` text NOT NULL,\n\t`icon` text DEFAULT 'flask' NOT NULL,\n\t`sort_order` integer DEFAULT 0 NOT NULL\n);",
      "CREATE TABLE `social_links` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`platform` text NOT NULL,\n\t`label` text NOT NULL,\n\t`url` text NOT NULL,\n\t`sort_order` integer DEFAULT 0 NOT NULL,\n\t`visible` integer DEFAULT true NOT NULL\n);",
      "CREATE TABLE `teaching` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`term` text NOT NULL,\n\t`course` text NOT NULL,\n\t`role` text DEFAULT 'Teaching Assistant' NOT NULL,\n\t`institution` text,\n\t`description` text,\n\t`url` text,\n\t`sort_order` integer DEFAULT 0 NOT NULL\n);"
    ]
  },
  {
    "name": "0001_black_silver_fox",
    "statements": [
      "ALTER TABLE `blog_posts` ADD `source` text;",
      "ALTER TABLE `profile` ADD `logo` text;",
      "ALTER TABLE `profile` ADD `hero_image` text;",
      "ALTER TABLE `profile` ADD `hero_video` text;",
      "ALTER TABLE `profile` ADD `hero_subtitle` text;",
      "ALTER TABLE `profile` ADD `hero_tagline` text;",
      "ALTER TABLE `profile` ADD `hero_text` text;",
      "ALTER TABLE `profile` ADD `about_page_markdown` text;",
      "ALTER TABLE `profile` ADD `about_page_image` text;",
      "ALTER TABLE `profile` ADD `address_line1` text;",
      "ALTER TABLE `profile` ADD `address_line2` text;",
      "ALTER TABLE `profile` ADD `research_intro` text;",
      "ALTER TABLE `profile` ADD `teaching_intro` text;",
      "ALTER TABLE `profile` ADD `media_intro` text;",
      "ALTER TABLE `profile` ADD `blog_intro` text;",
      "ALTER TABLE `publications` ADD `poster_url` text;",
      "ALTER TABLE `publications` ADD `video_url` text;",
      "ALTER TABLE `publications` ADD `slides_url` text;",
      "ALTER TABLE `publications` ADD `image` text;",
      "ALTER TABLE `publications` ADD `venue_tag` text;",
      "ALTER TABLE `teaching` ADD `image` text;",
      "ALTER TABLE `teaching` ADD `terms` text;"
    ]
  }
];
