/**
 * Bundles the SQL migrations in ./drizzle into src/db/migrations.ts so the app can
 * migrate itself at runtime (serverless hosts do not ship the drizzle folder).
 * Runs automatically after `npm run db:generate`.
 */
import fs from "node:fs";
import path from "node:path";

const dir = path.resolve("drizzle");
const journal = JSON.parse(fs.readFileSync(path.join(dir, "meta", "_journal.json"), "utf8")) as { entries: { tag: string }[] };
const migrations = journal.entries.map((e) => {
  const sql = fs.readFileSync(path.join(dir, `${e.tag}.sql`), "utf8");
  const statements = sql.split("--> statement-breakpoint").map((s) => s.trim()).filter(Boolean);
  return { name: e.tag, statements };
});
const out = `// AUTO-GENERATED by scripts/sync-migrations.ts — do not edit. Run \`npm run db:generate\`.
export interface Migration { name: string; statements: string[] }
export const migrations: Migration[] = ${JSON.stringify(migrations, null, 2)};
`;
fs.writeFileSync(path.resolve("src/db/migrations.ts"), out);
console.log(`✔ Bundled ${migrations.length} migration(s) into src/db/migrations.ts`);
